#!/usr/bin/env python3
"""Build the pipeline's NGSI-LD @context from the T.O.P. cr-domain context.

Merges two layers into one dereferenceable file the broker fetches from
the web service:

1. The vendored T.O.P. cr-domain NGSI-LD context artifact
   (infra/seed/top-cr-v1.ngsi-context.jsonld, Apache-2.0, generated by
   the-ontology-project's cr-domain/docs/build_dist.py). Its remote ETSI
   core-context reference is dropped: NGSI-LD brokers append the core
   context implicitly, and keeping the file self-contained lets the whole
   stack run with no internet access at all.

2. A supplement layer:
   - cr: instance-level terms that T.O.P.'s own worked examples and SDTM
     projections use (cr:screeningNumber, cr:visitStatus, ...) but that
     the generated context omits because they are not declared classes or
     object properties in the formal ontology.
   - a small pne: namespace for demo-only terms that are not T.O.P.
     vocabulary at all (study title, arm display name, ...).

Usage: python3 infra/scripts/build-context.py
Writes: web/public/context/pne-context.jsonld (committed; rerun on change)
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "infra/seed/top-cr-v1.ngsi-context.jsonld"
DEST = ROOT / "web/public/context/pne-context.jsonld"

PNE_NS = "https://top.scientix.ai/pne-ce/v1#"

# cr: terms used by T.O.P. cr-domain examples/ and projections/ but absent
# from the generated NGSI context (instance-level data properties, plus
# the Participant class and its relationships).
CR_SUPPLEMENT_TYPES = ["Participant"]
CR_SUPPLEMENT_RELATIONSHIPS = ["forStudy", "assignedToArm", "forParticipant"]
CR_SUPPLEMENT_PROPERTIES = [
    "studyId",
    "screeningNumber",
    "participantStatus",
    "visitStatus",
    "visitType",
    "visitMode",
    "windowStatus",
    "actualStartDate",
    "actualEndDate",
    "visitNumber",
    "visitName",
    "plannedStudyDay",
    "armCode",
    "parameterCode",
    "numericValue",
    "unit",
    "referenceRangeLow",
    "referenceRangeHigh",
    "interpretation",
    "sex",
    "country",
]

# Demo-only presentation terms; deliberately not minted into cr:.
PNE_TERMS = ["studyTitle", "studyPhase", "armName", "endpointText"]

# Generic display name, mapped to schema.org rather than minting our own.
NAME_TERM = ("name", "https://schema.org/name")


def main() -> None:
    src = json.loads(SRC.read_text())
    merged: dict = {}
    for part in src["@context"]:
        if isinstance(part, dict):
            merged.update(part)
        # string parts (the remote ETSI core context) are intentionally
        # dropped; the broker appends the core context itself

    for term in CR_SUPPLEMENT_TYPES + CR_SUPPLEMENT_PROPERTIES:
        merged.setdefault(term, f"cr:{term}")
    for term in CR_SUPPLEMENT_RELATIONSHIPS:
        merged.setdefault(term, {"@id": f"cr:{term}", "@type": "@id"})

    merged["pne"] = PNE_NS
    for term in PNE_TERMS:
        merged.setdefault(term, f"pne:{term}")
    merged.setdefault(*NAME_TERM)

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(
        json.dumps({"@context": merged}, indent=2, sort_keys=True) + "\n"
    )
    print(f"wrote {DEST.relative_to(ROOT)} ({len(merged)} terms)")


if __name__ == "__main__":
    main()
